### ISSUE TITLE
Compatibility with Python 3

### ISSUE THREAD

**Issue by wjlei1990** [caiociardelli/gladm25#1]
Hi Caio,

I noticed in the utility [python script](https://github.com/caiociardelli/gladm25/blob/main/utils/create_extra_depth_slice.py#L130), you have:
```
FILE.write (header.decode ('utf-8'))
```

I am using python 3 and I think in python 3 you don't need the `decode`.

Are you using python2?

**Comment by caiociardelli** [comment]
Hi, Wenjie.

Yes, I am. That is why I wrote the code to be compatible both with Python2
and Python3. Python3 is around for a long time, but Python2 is still used
for many people. In my case, the reason is my outdated Linux version, in
which Python2 is the default. When I finish my Ph.D. I shall update my
system and Python3 will be the default.

Caio

Em qua, 11 de nov de 2020 19:24, Wenjie Lei <notifications@github.com>
escreveu:

**Comment by wjlei1990** [comment]
I am using python3 and the code just gives me errors...

I have to delete the `decode()` to make it work.

**Comment by caiociardelli** [comment]
Oh, I see. I thoght that it was working for you, just that .decide() was
not necessary. I will fix that. Thanks for letting me know!

Caio

Em qui, 12 de nov de 2020 11:25, Wenjie Lei <notifications@github.com>
escreveu:

**Comment by caiociardelli** [comment]
Problem fixed.

I replaced the ".decode('utf-8')" by ".encode ().decode ('utf-8')". In my
computer, it works with both Python2 and Python3. But let me know in case
you still have any problems.

Best,

Caio

Em qui., 12 de nov. de 2020 às 11:56, Caio Ciardelli <
caio.ciardelli@gmail.com> escreveu:
